server:
  port: 5071
 
spring:
  profiles:
    active: list1
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: Alex1993!
    platform: postgres
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
#Opzioni Open Feign    
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
      
#Configurazione levello di Log PriceClient 
logging:
  level:
    com:
      xantrix:
        webapp:
          controller:
            PriceClient: DEBUG
            
    #Opzioni Accesso Servizio gestuser            
gestuser:
  password: BimBumBam_2018
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  # ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: Alex1993!
    
