server:
  port: 8019
spring:
  application:
    name: GestUser
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: localhost
      password: Alex1993!
      port: 37017
      username: alex
